name: testing dockerhub push
on:
  push:
    branches:
      - dockerhub
      - master
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            image_name: [cloudsim_sim, cloudsim_bridge, subt_shell, subt_sim_entry]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install base dependencies
        run: |
          sudo apt update;
          sudo apt-get install -y docker

      - name: Run build script
        run: |
            cd docker
            bash +xe ./build.bash ${{ matrix.image_name }}

       # - name: Tag image
       #         run: |
       #            docker tag ${{ matrix.image_name }}:latest jlrivero/subt:${{ matrix.image_name }}_latest

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to docker registry
        uses: actions-hub/docker@master
        env:
          IMAGE: ${{ matrix.image_name }}
          TAG: jlrivero/subt:${{ matrix.image_name }}_latest
        with:
          args: push ${IMAGE_TAG}
